<a href="https://colab.research.google.com/github/Pathak1511/1stProject/blob/main/exp-01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
x=int(input("Enter a number:"))
y=int(input("Enter second number:"))
if(x==45):
    print("Its 45")
else:
    print(x+y)

Enter a number:6
Enter second number:8
14


In [2]:
x=10
type(x)
p=[10,12,14,16,18]
p

[10, 12, 14, 16, 18]

In [3]:
p.insert(2,25)
p

[10, 12, 25, 14, 16, 18]

In [4]:
y=[10,2,3,4,5,6,[4,5,6,],7]
y

d2={12:"hello",(1,2,3,4):[4,5,6,7]}
d2[12]

'hello'

In [5]:
x=input("enter the username:")
y=input("enter the password:")
if(x=='dikshant') and (y=='dikshant'):
  print("successful")
else:
  print("Try again")
x=input("enter the username:")
if(x=='dikshant'):
  y=input("enter the password:")
  if(y=="dikshant"):
    print("welcome")
  else:
    print("Try again")

enter the username:hritik
enter the password:dikshant
Try again
enter the username:dikshant
enter the password:dikshant
welcome


In [6]:
for i in range(1,10,2):
  print(i)
for i in range(10):
  print(i)
l=['dikshant','mayank','abbas']
for i in range(len(l)):
  print(i)

1
3
5
7
9
0
1
2
3
4
5
6
7
8
9
0
1
2


In [7]:
s=[]
l=['dikshant','mayank','abbas']
for i in l:
  print(str(len(i)),":",i)
  s.append(len(i))
print(s)

8 : dikshant
6 : mayank
5 : abbas
[8, 6, 5]


In [8]:
def name():
  print('dikshant')
name()
def name(x):
  print("dikshant and",x)
name('mayank')
name('abbas')

dikshant
dikshant and mayank
dikshant and abbas


In [9]:
import numpy as np 
x=np.array([10,11,12,13])
print(x)

[10 11 12 13]


In [10]:
x=np.array([[10,11,12,13],[14,15,16,17],[18,19,20,21]])
print(x.ndim)
print(x)
print(x.sum())
#print(x.prod())
print(x.max())
print(x.min())
print(x.argmax())
print(x.argmin())

2
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
186
21
10
11
0


In [12]:
x[0,0]
y=x[:,-1:]
y
x.shape
b=x.reshape(4,3)
print(b)
x.transpose()
print(x)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [13]:
x=np.array([[10,11,12,13],[14,15,16,17]])
print(x)
a=0
a=np.arange(16).reshape(4,4)
a[1:3,:]
print(a)
a[1:3,2:]
print(a)
a=np.arange(18).reshape(3,3,2)
a

[[10 11 12 13]
 [14 15 16 17]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])