<a href="https://colab.research.google.com/github/Pathak1511/1stProject/blob/main/exp_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# using iris data from sklearn without target column as a unsupervised learning in k-means algo


In [7]:
import numpy as np
from sklearn.datasets import load_iris
import pandas as pd

In [6]:
df = load_iris()
df.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [14]:
newdf = df['data']
target = df['target']
print(newdf[0:5])
print(target[0:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [16]:
from sklearn.cluster import KMeans

In [21]:
model = KMeans(n_clusters=3,init='random',n_init=10,max_iter=100,tol=0.00002,random_state=0)

In [22]:
y = model.fit_predict(newdf)

In [23]:
from sklearn.metrics import confusion_matrix

In [30]:
cm = confusion_matrix(target,y)
print("Actual vs predicted")
print(df['target_names'])
print(cm)


Actual vs predicted
['setosa' 'versicolor' 'virginica']
[[50  0  0]
 [ 0 48  2]
 [ 0 14 36]]
